version: "3.7"

services:

    flask:
        build: ./flask
        container_name: flask
        environment:
            - APP_NAME=LatinMassRESTAPI
        expose:
            - 8000
        networks:
            - nginx_network
            
    nginx:
        build: ./nginx
        container_name: nginx
        ports:
            - "8000:80"
        depends_on:
            - flask
        networks:
            - nginx_network
            
networks:
    nginx_network:
        driver: bridge
        
